version: "3.8"

services:
    app:
        build: .
        container_name: real-estate-app
        ports:
            - "8080:8080"
        volumes:
            - ./src:/app
        # network_mode: "host"
