services:
    app:
        build: .
        container_name: real-estate-app
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/real_estate_db
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=123456
        depends_on:
            - db
        networks:
            - real-estate-network
        restart: always

    db:
        image: postgres:15
        container_name: real-estate-db
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=real_estate_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123456
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./db/init:/docker-entrypoint-initdb.d
        networks:
            - real-estate-network
        restart: always

networks:
    real-estate-network:
        driver: bridge

volumes:
    postgres_data:
